version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: always
    networks:
      - teaspoon-network
      - npm_default

  backend:
    build: ./backend
    ports:
      - "10.0.0.124:8001:8001"
    volumes:
      - ./backend/data:/app/data
    env_file:
      - .env
    restart: always
    networks:
      - teaspoon-network
      - npm_default

  minio:
    image: minio/minio:latest
    container_name: teaspoon-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    restart: always
    networks:
      - teaspoon-network
      - npm_default

networks:
  teaspoon-network:
    driver: bridge
  npm_default:
    external: true

volumes:
  minio_data:
