"""add recommended deadline

Revision ID: f47cb2c768da
Revises: 
Create Date: 2026-05-17 05:27:15.611123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47cb2c768da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('recommended_deadline', sa.String(), nullable=True))
    op.drop_column('assignments', 'isOptional')
    op.add_column('courses', sa.Column('lab_report_weight', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('lab_report_keep', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('lab_report_magen', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('total_credits', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weighted_sum', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('previous_total_credits', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('previous_weighted_sum', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('binary_credits', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('previous_binary_credits', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'previous_binary_credits')
    op.drop_column('users', 'binary_credits')
    op.drop_column('users', 'previous_weighted_sum')
    op.drop_column('users', 'previous_total_credits')
    op.drop_column('users', 'weighted_sum')
    op.drop_column('users', 'total_credits')
    op.drop_column('courses', 'lab_report_magen')
    op.drop_column('courses', 'lab_report_keep')
    op.drop_column('courses', 'lab_report_weight')
    op.add_column('assignments', sa.Column('isOptional', sa.BOOLEAN(), nullable=True))
    op.drop_column('assignments', 'recommended_deadline')
    # ### end Alembic commands ###
