"""change drop to keep

Revision ID: f5d445a91375
Revises: 2f9e8ae748d0
Create Date: 2026-05-17 05:29:56.655697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d445a91375'
down_revision: Union[str, Sequence[str], None] = '2f9e8ae748d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'hw_drop', new_column_name='hw_keep')
    op.alter_column('courses', 'ww_drop', new_column_name='ww_keep')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'hw_keep', new_column_name='hw_drop')
    op.alter_column('courses', 'ww_keep', new_column_name='ww_drop')
    # ### end Alembic commands ###
